server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.18.111
  rabbitmq:
    host: 192.168.18.111
    virtual-host: /fenge
    username: fenge
    password: fenge
auth:
  jwt:
    publicKeyPath: C:\\0615javaee\\javaeestudy\\workspace_idea01\\tmp\\rsa.pub # \u516C\u94A5\u5730\u5740
    expire: 2592000 # \u8FC7\u671F\u65F6\u95F4\uFF0C\u4E00\u4E2A\u6708
    cookieName: GMALL_TOKEN # cookie\u7684\u540D\u79F0
    userKeyName: USER-KEY # \u672A\u767B\u5F55\u8D2D\u7269\u8F66\u7684\u552F\u4E00\u6807\u8BC6
